/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "primo.h"

bool_t
xdr_primo_in (XDR *xdrs, primo_in *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->primo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_primo_out (XDR *xdrs, primo_out *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}
