/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "primo.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

primo_out *
primoproc_1(primo_in *argp, CLIENT *clnt)
{
	static primo_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PRIMOPROC,
		(xdrproc_t) xdr_primo_in, (caddr_t) argp,
		(xdrproc_t) xdr_primo_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
