/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRIMO_H_RPCGEN
#define _PRIMO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct primo_in {
	long primo;
};
typedef struct primo_in primo_in;

struct primo_out {
	bool_t res;
};
typedef struct primo_out primo_out;

#define PRIMO_PROG 0x31230000
#define PRIMO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRIMOPROC 1
extern  primo_out * primoproc_1(primo_in *, CLIENT *);
extern  primo_out * primoproc_1_svc(primo_in *, struct svc_req *);
extern int primo_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRIMOPROC 1
extern  primo_out * primoproc_1();
extern  primo_out * primoproc_1_svc();
extern int primo_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_primo_in (XDR *, primo_in*);
extern  bool_t xdr_primo_out (XDR *, primo_out*);

#else /* K&R C */
extern bool_t xdr_primo_in ();
extern bool_t xdr_primo_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRIMO_H_RPCGEN */
